name: Format

on: push

jobs:
  format-code:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
      YOUTUBE_VIDEO_ID: ${{ env.YOUTUBE_VIDEO_ID }}
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Take Screenshot
        run: python3 main.py

      - uses: stefanzweifel/git-auto-commit-action@v5