name: Format

on: push

jobs:
  format-code:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Take Screenshot
        run: python3 main.py

      - uses: stefanzweifel/git-auto-commit-action@v5